# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-27 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='datetime',
            field=models.DateTimeField(verbose_name='Date of publication'),
        ),
    ]
