# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', models.CharField(max_length=10000)),
                ('tags', models.CharField(max_length=1000)),
                ('time', models.DateTimeField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
