# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_blogentry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogentry',
            options={'verbose_name_plural': 'Blog entries'},
        ),
        migrations.AlterField(
            model_name='blogentry',
            name='content',
            field=models.TextField(max_length=10000),
        ),
    ]
