# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-22 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_auto_20180321_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('ServiceId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('acronym', models.CharField(max_length=10)),
                ('url', models.URLField()),
                ('desc', models.CharField(max_length=450)),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.DeleteModel(
            name='BlogEntry',
        ),
    ]
