# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_auto_20180321_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmittedTip',
            fields=[
                ('tipId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('tip', models.CharField(max_length=1000)),
            ],
        ),
    ]
