# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-22 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_delete_blogentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField(verbose_name='Date')),
                ('content', models.TextField(max_length=10000)),
            ],
        ),
    ]
