# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-22 17:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_service_phone_number'),
        ('MainApp', '0006_delete_blogentry'),
    ]

    operations = [
    ]
